package com.RestAPITest;

import org.testng.Assert;
import org.testng.annotations.Test;

import io.restassured.response.Response;

import static io.restassured.RestAssured.given;
/*
* given(): Prerequisite
* ---------------------------
* header,path parameter,query parameter,request payload , authrozation 
* 
*  
* when(): Action(Type of request)
* ---------------------------------
* GET,POST,PUT,PATCH,DELETE
* 
* 
* then():Validate Response
* -------------------------
* status code, status message, response time, response payload,headers,cookies
* 
* 
*/
public class Tc7_Cookies_HeaderValidation 
{
	
	
  @Test
  public void testCookies()
  {
	  Response res=given()
			  			.when().get("https://www.google.com/");
	  
	  /*
	   * Cookies generated by server
	   * Cookies are dynamic
	   * Expectation
	   * ================
	   * No two cookies have same value
	   * 
	   */
	  
	  //get the cookies details
	  res.then().log().cookies();
	  
	  //get the actual cookie
	  String actCookie=res.getCookie("NID");
	  String expCookie="BB1onQA962tbs4fM-pGOvrpQnmmOIP31JuV";
	  
	  Assert.assertFalse(actCookie.contains(expCookie),"Test Fail: Cookies are equal!");
	  System.out.println("Test Pass: Cookies are not equal!");
	  
	  
	  	  
	  
  }
  
  
  @Test
  public void headerValidation()
  {
	  Response res=given()
	  			.when().get("https://www.google.com/");
	  
	  
	  //get all header
	  res.then().log().headers();
	  
	  //get the header details
	  String actHeader=res.getHeader("Content-Type");
	  String expHeader="text/html; charset=ISO-8859-1";
	  
	  Assert.assertEquals(actHeader,expHeader);
	  System.out.println("Headers are equal!");
	  
	  
  }
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
}
